# Generated by Django 3.1.7 on 2021-04-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aelhanssalifornitures',
            name='month',
            field=models.CharField(default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aitmessaoudfornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binouidanefornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daouratefornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diguesafifornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hassanpremfornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imfoutfornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massirafornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myyousseffornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sididaouifornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sididrissfornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssmaachoufornitures',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
