# Generated by Django 3.1.7 on 2021-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barage', '0002_auto_20210402_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='aelhanssalifornitures',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aitmessaoudfornitures',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barageuploaded',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binouidanefornitures',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daouratefornitures',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diguesafifornitures',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hassanpremfornitures',
            name='year',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imfoutfornitures',
            name='year',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massirafornitures',
            name='year',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myyousseffornitures',
            name='year',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sididaouifornitures',
            name='year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sididrissfornitures',
            name='year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssmaachoufornitures',
            name='year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
