# Generated by Django 3.1.7 on 2021-04-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barage', '0003_auto_20210403_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aelhanssalifornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='aitmessaoudfornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='binouidanefornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='daouratefornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='diguesafifornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='hassanpremfornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='imfoutfornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='massirafornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='myyousseffornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sididaouifornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sididrissfornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='ssmaachoufornitures',
            name='month',
            field=models.CharField(max_length=4),
        ),
    ]
