# Generated by Django 3.2 on 2021-05-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barage', '0006_transfertmassira'),
    ]

    operations = [
        migrations.AddField(
            model_name='aelhanssalifornitures',
            name='aport',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binouidanefornitures',
            name='aport',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hassanpremfornitures',
            name='aport',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massirafornitures',
            name='aport',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myyousseffornitures',
            name='aport',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
