# Generated by Django 3.2 on 2021-05-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barage', '0007_auto_20210501_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiminoutineBilanHydr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.FloatField()),
                ('cote', models.FloatField()),
                ('reserve', models.FloatField()),
                ('varReserve', models.FloatField()),
                ('evaporation', models.FloatField()),
                ('vidange', models.FloatField()),
                ('deverse', models.FloatField()),
                ('v1', models.FloatField()),
                ('v2', models.FloatField()),
                ('soltania', models.FloatField()),
                ('total', models.FloatField()),
                ('volumeApp', models.FloatField()),
                ('debitApp', models.FloatField()),
            ],
        ),
    ]
