# Generated by Django 3.2 on 2021-05-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barage', '0008_timinoutinebilanhydr'),
    ]

    operations = [
        migrations.AddField(
            model_name='timinoutinebilanhydr',
            name='annee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timinoutinebilanhydr',
            name='mois',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timinoutinebilanhydr',
            name='jour',
            field=models.IntegerField(),
        ),
    ]
